-- =========================================================
-- SinSangPick (신상픽) Seed Data for Supabase
-- =========================================================

INSERT INTO public.products (
    id, name, brand, category, sub_category, item_type, image, release_date, price, discount_rate, 
    overall_rating, rating_count, detailed_rating, fresh_metrics, description, best_quotes, stores, 
    repurchase_percent, calories, volume, is_today, is_hot
) VALUES
(
    'prod-01',
    '꼬북칩 초코츄러스맛 더블크런치',
    '오리온',
    '과자',
    '스낵/칩',
    'packaged',
    'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop&q=80',
    '2026.09.02 출시',
    1800,
    15,
    4.8,
    542,
    '{"taste": 4.9, "value": 4.5, "portion": 4.2, "repurchase": 4.8}'::jsonb,
    NULL,
    '4겹 층마다 진한 벨기에산 초콜릿과 슈가 토핑을 듬뿍 발라 바삭함과 달콤함이 극대화된 스낵입니다.',
    ARRAY['진짜 존맛.. 계속 손이 가요!', '초코 맛이 진하고 바삭해요', '츄러스 맛이 은근 잘 어울려요'],
    ARRAY['CU', 'GS25', '세븐일레븐'],
    96,
    432,
    '80g',
    true,
    true
),
(
    'prod-02',
    '연세우유 피스타치오 생크림빵',
    '연세우유 (CU단독)',
    '편의점',
    '디저트빵',
    'packaged',
    'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    '2026.09.02 출시',
    3400,
    0,
    4.9,
    712,
    '{"taste": 5.0, "value": 4.6, "portion": 5.0, "repurchase": 4.9}'::jsonb,
    NULL,
    '원물 피스타치오 페이스트가 들어간 묵직하고 고소한 생크림이 빵 터질 듯 가득 들어있습니다.',
    ARRAY['피스타치오 원물 크림이 빵 터질 듯 가득!', '인공향 절대 아니고 진짜 꼬소해요'],
    ARRAY['CU'],
    97,
    495,
    '145g',
    true,
    true
),
(
    'prod-03',
    '포카칩 먹태청양마요맛 에디션',
    '오리온',
    '과자',
    '스낵/칩',
    'packaged',
    'https://images.unsplash.com/photo-1566478989037-e2b9527bd087?w=600&auto=format&fit=crop&q=80',
    '2026.09.01 출시',
    1700,
    20,
    4.6,
    388,
    '{"taste": 4.7, "value": 4.1, "portion": 3.9, "repurchase": 4.5}'::jsonb,
    NULL,
    '100% 생감자칩의 바삭함에 고소한 먹태 분말과 매콤달콤 청양마요 시즈닝의 밸런스.',
    ARRAY['알싸한 청양마요가 맥주 안주로 딱!', '바삭하고 짭조름해서 최고예요'],
    ARRAY['CU', 'GS25'],
    92,
    380,
    '66g',
    false,
    false
),
(
    'fruit-01',
    '햇사레 프리미엄 당도선별 복숭아',
    '햇사레 (충북 음성·이천)',
    '과일',
    '복숭아',
    'fresh',
    'https://images.unsplash.com/photo-1595158364153-23961fa633df?w=600&auto=format&fit=crop&q=80',
    '산지직송 제철',
    24900,
    15,
    4.8,
    890,
    '{"taste": 4.9, "value": 4.4, "portion": 4.6, "repurchase": 4.8}'::jsonb,
    '{"sweetness": 4.9, "freshness": 4.9, "texture": 4.8, "value": 4.4}'::jsonb,
    '비파괴 당도 선별기로 13~14 Brix 이상의 고당도만 엄선한 과즙 가득 제철 복숭아입니다.',
    ARRAY['한 입 베어물면 꿀물 과즙이 뚝뚝 떨어져요 🍑', '선물용으로 샀는데 상태 최상이고 너무 달아요'],
    ARRAY['마켓컬리', '쿠팡프레시', '대형마트'],
    96,
    NULL,
    '2kg (6~8과)',
    false,
    true
),
(
    'rest-01',
    '전통 평양냉면 명가 순메밀 100%',
    '우래옥 / 을밀대 계열',
    '외식 메뉴',
    '냉면',
    'restaurant',
    'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&auto=format&fit=crop&q=80',
    '사계절 별미',
    16000,
    0,
    4.8,
    1420,
    '{"taste": 4.9, "value": 4.2, "portion": 4.6, "repurchase": 4.9}'::jsonb,
    NULL,
    '은은한 육향과 진한 한우 육수에 거칠고 구수한 메밀면이 어우러진 서울 최고의 평양냉면.',
    ARRAY['국물 한 모금 마시면 은은한 육향이 입안 가득 퍼집니다 🍜', '해장으로 이것보다 좋은 냉면은 없어요'],
    ARRAY['서울 중구', '마포구', '강남구'],
    97,
    NULL,
    '1인분',
    false,
    true
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    overall_rating = EXCLUDED.overall_rating,
    rating_count = EXCLUDED.rating_count,
    price = EXCLUDED.price;
